name: Release
on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Scala Blockchain Downloader ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: CHANGELOG.md
      - id: step_upload_url
        run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"

  build-publish-all:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.x'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt update && sudo apt install -y build-essential
    - name: Make
      run: make

    - name: Release for macOS
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./bin/macos-x64/scala-blockchain-downloader
          asset_name: scala-blockchain-downloader-darwin-x64
          asset_content_type: application/octet-stream

    - name: Release for linux
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./bin/linux-x64/scala-blockchain-downloader
          asset_name: scala-blockchain-downloader-linux-x64
          asset_content_type: application/octet-stream

    - name: Release for windows
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./bin/win-x64/scala-blockchain-downloader
          asset_name: scala-blockchain-downloader-win-x64.exe
          asset_content_type: application/octet-stream