name: Build
on: [push, pull_request]

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.x'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt update && sudo apt install -y build-essential
    - name: Make
      run: make